// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ideas.sql

package ideas

import (
	"context"
	"time"
)

const createIdea = `-- name: CreateIdea :one

WITH i AS (
    INSERT INTO ideas (author_id, title, description, course, category, slots)
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, author_id, title, description, course, category, slots, status, created_at
)
SELECT i.id, i.title, i.description, i.course, i.category, i.slots, i.status, i.created_at,
       u.id AS author_id, u.name AS author_name
FROM i
JOIN users u ON u.id = i.author_id
`

type CreateIdeaParams struct {
	AuthorID    int64
	Title       string
	Description string
	Course      string
	Category    string
	Slots       int32
}

type CreateIdeaRow struct {
	ID          int64
	Title       string
	Description string
	Course      string
	Category    string
	Slots       int32
	Status      string
	CreatedAt   time.Time
	AuthorID    int64
	AuthorName  string
}

// Create e List devolvem as mesmas colunas, na mesma ordem: assim as structs geradas são conversíveis entre si.
func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (CreateIdeaRow, error) {
	row := q.db.QueryRow(ctx, createIdea,
		arg.AuthorID,
		arg.Title,
		arg.Description,
		arg.Course,
		arg.Category,
		arg.Slots,
	)
	var i CreateIdeaRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Course,
		&i.Category,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.AuthorID,
		&i.AuthorName,
	)
	return i, err
}

const listIdeas = `-- name: ListIdeas :many
SELECT i.id, i.title, i.description, i.course, i.category, i.slots, i.status, i.created_at,
       u.id AS author_id, u.name AS author_name
FROM ideas i
JOIN users u ON u.id = i.author_id
ORDER BY i.created_at DESC, i.id DESC
`

type ListIdeasRow struct {
	ID          int64
	Title       string
	Description string
	Course      string
	Category    string
	Slots       int32
	Status      string
	CreatedAt   time.Time
	AuthorID    int64
	AuthorName  string
}

func (q *Queries) ListIdeas(ctx context.Context) ([]ListIdeasRow, error) {
	rows, err := q.db.Query(ctx, listIdeas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdeasRow
	for rows.Next() {
		var i ListIdeasRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Course,
			&i.Category,
			&i.Slots,
			&i.Status,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
