// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package ideas

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Idea struct {
	ID          int64
	AuthorID    int64
	Title       string
	Description string
	Course      string
	Category    string
	Slots       int32
	Status      string
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	DiscordID pgtype.Text
	Name      string
	AvatarUrl pgtype.Text
	Course    pgtype.Text
	CreatedAt time.Time
}
