// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package auth

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.name, u.avatar_url, u.course
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	AvatarUrl *string `json:"avatar_url"`
	Course    *string `json:"course"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AvatarUrl,
		&i.Course,
	)
	return i, err
}

const upsertDiscordUser = `-- name: UpsertDiscordUser :one
INSERT INTO users (discord_id, name, avatar_url)
VALUES ($1, $2, $3)
ON CONFLICT (discord_id) DO UPDATE SET name = EXCLUDED.name, avatar_url = EXCLUDED.avatar_url
RETURNING id
`

type UpsertDiscordUserParams struct {
	DiscordID *string `json:"discord_id"`
	Name      string  `json:"name"`
	AvatarUrl *string `json:"avatar_url"`
}

// Nome e foto acompanham o Discord: são regravados a cada login.
func (q *Queries) UpsertDiscordUser(ctx context.Context, arg UpsertDiscordUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDiscordUser, arg.DiscordID, arg.Name, arg.AvatarUrl)
	var id int64
	err := row.Scan(&id)
	return id, err
}
