// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package auth

import (
	"time"
)

type Idea struct {
	ID          int64     `json:"id"`
	AuthorID    int64     `json:"author_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Course      string    `json:"course"`
	Category    string    `json:"category"`
	Slots       int32     `json:"slots"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type Session struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        int64     `json:"id"`
	DiscordID *string   `json:"discord_id"`
	Name      string    `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	Course    *string   `json:"course"`
	CreatedAt time.Time `json:"created_at"`
}
