// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package auth

import (
	"time"
)

type Idea struct {
	ID          int64
	AuthorID    int64
	Title       string
	Description string
	Course      string
	Category    string
	Slots       int32
	Status      string
	CreatedAt   time.Time
}

type Session struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
}

type User struct {
	ID        int64
	DiscordID *string
	Name      string
	AvatarUrl *string
	Course    *string
	CreatedAt time.Time
}
